### ISSUE TITLE
POST and PUT don't pass "body" to the handler

### ISSUE THREAD

**Issue by mludvig** [studio3104/pytest-chalice#10]
I tried to test a Chalice handler that responds to `POST` with a `body=...` but whatever I do It always comes out as `None` on my app side.

This is my test:

```python
    response = client.post('/mm?abcd=efgh', 
        headers={"X-Something": "Some Thing"},
        body=json.dumps({
            "message_id": "1234-1234",
        })
    )
```

However in my `/mm` handler on the app side I always get `app.current_request.json_body` as `None`.  The *headers* are passed over but the *body* isn't. Can you have a look a it please?

**Comment by studio3104** [comment]
Could you try with a header that includes `'Content-Type': 'application/json'`?

**Comment by mludvig** [comment]
That works, thanks! It  may be good to document this, it's a bit non-obvious.

Also I suggest you bump up the version to 1.x.x as 0.0.4 doesn't really give much confidence at first :)

Thanks for `pytest-chalice`, it makes testing so much easier!

**Comment by studio3104** [comment]
Thank you very much for your trial, I am probably going to bump the version!
