### ISSUE TITLE
Would love more examples

### ISSUE THREAD

**Issue by bzaks1424** [studio3104/pytest-chalice#9]
I've created a relatively robust chalice app, and am literally just getting into my very first foray of unit testing (having never done it in python before). 

I've created the same confttest and test_app file you created, but honestly have no idea where to go from there.

**Comment by studio3104** [comment]
Thanks for giving me a feedback, I'm gonna add some more examples and enhance the document ASAP
BTW, what do you want concretely for the next? You've gotten succeeded as the example, right?
